module.exports.abonementsConstants = {
  ABONEMENTS_SORT_NAMES: ['number', 'visits_quantity', 'status', 'date_start', 'date_end', 'user_created_id'],
  ABONEMENTS_SORT_TYPES: ['ASC', 'DESC'],
  ABONEMENTS_FULL_SORT_NAMES: [
    'clients.name',
    'clients.surname',
    'clients.patronymic',
    'birthday',
    'data_create',
    'abonements.abonement_id',
    'abonements.visits_quantity',
    'abonements.visits_left',
    'abonements.status_id',
    'abonements.date_start',
    'abonements.date_end',
    'abonements.user_created_id',
  ],
  ABONEMENTS_FULL_SORT_TYPES: ['ASC', 'DESC'],
  ABONEMENTS_FULL_FILTERS_NAMES: [
    'clients.name',
    'clients.surname',
    'clients.patronymic',
    'abonements.abonement_id',
    'abonements.visits_quantity',
    'abonements.visits_left',
    'abonements.status_id',
    'abonements.date_start',
    'abonements.date_end',
  ],
  ABONEMENTS_FULL_CLIENT_COLUMNS: [
    'client_id',
    'client_birthday',
    'client_name',
    'client_patronymic',
    'client_surname',
    'client_gender',
  ],
  ABONEMENTS_FULL_RELATIVE_COLUMNS: [
    'relative_id',
    'relative_name',
    'relative_patronymic',
    'relative_surname',
    'relative_type_id',
    'relative_telephone',
  ],
  ABONEMENTS_FULL_ABONEMENT_COLUMNS: [
    'abonement_id',
    'visits_quantity',
    'visits_left',
    'status_type',
    'status',
    'date_create',
    'date_start',
    'date_end',
    'user_created_id',
    'branch_id',
  ],
  ABONEMENTS_FULL_FILTERS: {
    status: [1, 2, 3, 4, 5],
  },
  ABONEMENTS_FULL_FILTERS_TABLES_COLUMNS_ASSOTIATIONS: {
    abonememts: '',
    events: '',
  },
  // 0 - мальчик, 1 - девочка
  GENDER_TYPES: [0, 1],
};
