name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "Error: Docker credentials not provided"
            exit 1
          fi
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t repertuar/backend-app:latest .
          docker tag repertuar/backend-app:latest repertuar/backend-app:${GITHUB_SHA:0:7}

      - name: Push Docker image
        run: |
          docker push repertuar/backend-app:latest
          docker push repertuar/backend-app:${GITHUB_SHA:0:7}
